services:
  app:
    build:
      context: ../../
      dockerfile: ./deploy/common/Dockerfile
    container_name: app
    depends_on:
      - clickhouse
      - db
    ports:
      - "${SERVER_PORT}:8080"
    env_file:
      - path: ./.env
    restart: unless-stopped
    networks:
      - general

  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5439:5432"
    env_file:
      - path: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - general

  clickhouse: 
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes: 
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - general

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - general

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - general
    depends_on:
      - prometheus
    volumes:
      - ./grafana/runtime-data:/var/lib/grafana
      - ./grafana/datasources/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yml

volumes:
  postgres_data:
  clickhouse_data:

networks:
  general:
    driver: bridge
