stages:
  - common

variables:
  GO_VERSION: "1.23.2"

job_common:
  stage: common
  image: golang:${GO_VERSION}-alpine
  before_script:
    - apk add --no-cache bash curl git shadow
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin
    - adduser -D -u 1000 appuser
    - su appuser -c "whoami"
  script:
    - su appuser -c '
        cd ./app &&
        export GOFLAGS="-buildvcs=false" &&
        if [ -n "$(gofmt -l .)" ]; then
          echo "Go code is not formatted. Please run go fmt ./...";
          gofmt -d .;
          exit 1;
        fi &&
        echo "Start linter" &&
        golangci-lint run &&
        echo "Start build" &&
        go build -v ./... &&
        echo "Start test" &&
        go test ./... -v --tags=integration
      '
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never
