version: "2"

run:
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    depguard:
      rules:
        log:
          files:
            - $all
          deny:
            - pkg: log
            - pkg: log/slog
    errcheck:
      check-type-assertions: true
      check-blank: false
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        shadow:
          strict: true
    revive:
      rules:
        - name: var-naming
          arguments:
            - []
            - []
            - [[], [], [{skipPackageNameChecks: true}]]
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
severity:
  default: error
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

